#! /bin/bash

USER=alex
KEY=700be00a-4e23-11e0-833b-90e6ba4b8b9a
HOST=localhost
#HOST=128.61.120.161
HOST=192.168.1.102

VERB=$1
shift
ACTION=$1
shift
for i in $@; do
    A="$A -d $i"
done

curl -X $VERB $A "$USER:$KEY@$HOST:3000/api/$ACTION"
echo
