#! /bin/bash

USER=alex
KEY=99bb1eca-4c8e-11e0-8525-90e6ba4b8b9a
#HOST=128.61.120.161
HOST=143.215.118.119

VERB=$1
shift
ACTION=$1
shift
for i in $@; do
    A="$A -d $i"
done

curl -X $VERB $A "$USER:$KEY@$HOST:3000/api/$ACTION"
echo
